export default [
    {
        id: 1,
        name: 'Anniversary',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
        images: ['a', 'b', 'c', 'd', 'e', 'f'],
        datetime: '2017-06-05 12:10:00 PM',
        tags: ['aniv', 'Celebration', 'Family', 'Merrage', 'Sample 1', 'Another Sample'],
        location: 'Premier Center, Makati City',
        sessions: [],
    },
    {
        id: 2,
        name: 'Christmas Party',
        description: 'Ipsum dolor sit amet, consectetur adipisicing elit.',
        images: [],
        datetime: '2017-06-05 12:10:00 PM',
        tags: [],
        location: 'Libertad, Mandaluyong City',
        sessions: [],
    },
    {
        id: 3,
        name: 'New Year',
        description: 'Dolor sit amet, consectetur adipisicing elit.',
        images: ['a', 'b', 'c'],
        datetime: '2017-06-05 12:10:00 PM',
        tags: [],
        location: 'San Antonio, Pasig City',
        sessions: [],
    },
    {
        id: 4,
        name: 'Birth Day',
        description: 'Sit amet, consectetur adipisicing elit.',
        images: ['a'],
        datetime: '2017-06-05 12:10:00 PM',
        tags: [],
        location: '',
        sessions: [],
    },
    {
        id: 5,
        name: 'Wedding',
        description: 'Consectetur adipisicing elit. Accusamus eius cumque.',
        images: [],
        datetime: '2017-06-05 12:10:00 PM',
        tags: [],
        location: '',
        sessions: [],
    },
];
